
package rp3.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MDMName", targetNamespace = "http://mdm.service.rp3/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MDMName {


    /**
     * 
     * @param getUserListRequest
     * @return
     *     returns rp3.client.UserListResponse
     */
    @WebMethod
    @WebResult(name = "GetUserListResponse", targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://mdm.service.rp3/", className = "rp3.client.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://mdm.service.rp3/", className = "rp3.client.GetUserListResponse")
    public UserListResponse getUserList(
        @WebParam(name = "GetUserListRequest", targetNamespace = "")
        UserListRequest getUserListRequest);

}
