
package rp3.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MDMServiceName", targetNamespace = "http://mdm.service.rp3/", wsdlLocation = "http://localhost:9898/MDM?wsdl")
public class MDMServiceName
    extends Service
{

    private final static URL MDMSERVICENAME_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(rp3.client.MDMServiceName.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = rp3.client.MDMServiceName.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9898/MDM?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9898/MDM?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MDMSERVICENAME_WSDL_LOCATION = url;
    }

    public MDMServiceName(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDMServiceName() {
        super(MDMSERVICENAME_WSDL_LOCATION, new QName("http://mdm.service.rp3/", "MDMServiceName"));
    }

    /**
     * 
     * @return
     *     returns MDMName
     */
    @WebEndpoint(name = "MDMPortName")
    public MDMName getMDMPortName() {
        return super.getPort(new QName("http://mdm.service.rp3/", "MDMPortName"), MDMName.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDMName
     */
    @WebEndpoint(name = "MDMPortName")
    public MDMName getMDMPortName(WebServiceFeature... features) {
        return super.getPort(new QName("http://mdm.service.rp3/", "MDMPortName"), MDMName.class, features);
    }

}
